create table user
(
    user_id             integer generated by default as identity
        primary key,
    user_name           varchar(50)  not null
        unique,
    user_email          varchar(255) not null
        unique,
    account_creation_time timestamp,
    user_role           varchar(50),
    user_avatar         bytea,
    password              varchar(50)  not null
);

alter table user
    owner to postgres;

create table directory
(
    directory_id          integer generated by default as identity
        primary key,
    user_id             integer
        references user
            on delete cascade,
    directory_name        varchar(50) not null,
    directory_is_visible  smallint,
    directory_is_favorite smallint
);

alter table directory
    owner to postgres;

create table project
(
    project_id               integer generated by default as identity
        primary key,
    directory_id             integer
        references directory
            on delete cascade,
    user_id                integer
        references user
            on delete cascade,
    project_name             varchar(50) not null
        unique,
    project_is_visible       smallint,
    project_is_favorite      smallint,
    time_of_project_creation timestamp,
    project_category         varchar(50) not null,
    project_container        bytea
);

alter table project
    owner to postgres;

create table note
(
    note_id               integer generated by default as identity
        primary key,
    user_id             integer
        references user
            on delete cascade,
    time_of_note_creation timestamp,
    note_text             varchar(500) not null
);

alter table note
    owner to postgres;

insert into user(user_name, user_email, account_creation_time,user_role, password) values ('testName','testEmail','2023-04-15 00:06:33.000000','USER_ROLE','testPassword');
insert into directory( user_id,directory_name) values (1,'testDirectoryName');
insert into note( user_id, time_of_note_creation, note_text) values (1, '2023-04-15 00:04:55.000000', 'test note text');
